env: test5
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.1.5:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
